#!/bin/bash

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ACTION=$1

[ -z "$PROJECT_DIR" ] && PROJECT_DIR=$SCRIPT_DIR
[ -z "$CONFIGURATION_TEMP_DIR" ] && CONFIGURATION_TEMP_DIR=$SCRIPT_DIR/build
[ -z "$CONFIGURATION_BUILD_DIR" ] && CONFIGURATION_BUILD_DIR=$SCRIPT_DIR/install
[ -z "$ACTION" ] && ACTION="build"
[ -z "$PRODUCT_NAME" ] && PRODUCT_NAME="libturbojpeg"
[ -z "$CONFIGURATION" ] && CONFIGURATION="Release"

"$PROJECT_DIR"/build.sh "$CONFIGURATION_TEMP_DIR" "$CONFIGURATION_BUILD_DIR" "$ACTION" "$PRODUCT_NAME" "$CONFIGURATION"




